---
name: Check file name case

on:
  pull_request:
    branches:
      - main

jobs:
  case:
    name: Check for case being inconsistent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["docs"]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Case check action
        uses: ConsenSys/github-actions/docs-case-check@7256f3d39c7bb71ec4ca9fc6078991302d4c8650
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOC_DIR: ${{ matrix.folder }}
          SKIP_TEST: true
