---
name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  case:
    uses: ./.github/workflows/case.yml
  build:
    needs: [lint, case]
    uses: ./.github/workflows/build.yml
  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Release
        uses: Consensys/github-actions/docs-release@7256f3d39c7bb71ec4ca9fc6078991302d4c8650
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_RELEASE: true
